version: "3.7"

services:
  api:
    container_name: django_api
    image: python:3.9

    environment:
      - LANG='en_US.UTF-8'
      - PYTHONDONTWRITEBYTECODE=1
    tty: true
    working_dir: /root/
    volumes:
      - ../api/:/root/
    command: >
      /bin/bash -c "
        python -m venv venv/ || true &&
        venv/bin/pip install pip setuptools -U &&
        venv/bin/pip install wheel &&
        venv/bin/pip install -r requirements.txt &&
        bash
      "
    privileged: true
    ports:
    - "8032:8032"
  
  postgres:
    container_name: django_postgres
    image: postgres:13
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django
      POSTGRES_DB: django
    volumes:
      - ../data/postgresql/:/var/lib/postgresql/
    expose:
      - "5432"
